title: What???...Punctuation!!!
description: This project explores expressive punctuation patterns across 10 subreddits. 
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-minimal
